---

# syncthing
syncthing__dependencies_ferm: True

device_moto:
  - id: "OBLFSDP-QPD4BRP-EZXNANV-6HQKBJP-IOOMXBQ-GEWDBID-HNDBXDM-WPEDOAO"
    name: "tapik"

devices_old:
  - id: "6W2RVAQ-GZBOGNF-G27AO2I-AXGRELU-6FGKXTM-WD2ELIN-L6W75F5-QUUWFQR"
    name: "old"
  - id: "36QXL6S-7RDFI7F-LX54RUP-IP5B3Y5-EMJRXPQ-DAQLQD5-GNB74MX-AEVJKAJ"
    name: "old"
  - id: "DNE2QC6-H2GSVJ6-KMKXHGI-IK5Y4J3-JW3M7BJ-WXXF5TH-F6XRFLW-DF2QKQ7"
    name: "old"
  - id: "XP46ALQ-PZKFHVZ-L5UMCYJ-DPOWGTM-HNYZ4UU-34PAF5D-I2IBTAP-NPBLJAP"
    name: "old"
  - id: "TFBQLDK-RSISSSY-R4HSPE2-5MOTUQK-LTHMH3A-VU7GVH3-HSDXGOM-MRMILAV"
    name: "old"
  - id: "DOLMZMR-NOAWENJ-W46EOMK-4TSKXU5-ZML6X2Z-TF5XIPF-IGNPQCN-JAGS4QH"
    name: "old"
  - id: "26HQMS3-G2G6UA4-URUKOQD-TCPWXXM-ZJBEWRZ-RCV3IPQ-W2LIOSQ-44RZ6QZ"
    name: "old"
  - id: "YEAT6S3-SS3SIR2-CA5AA3L-CW74SI5-7MGVDL2-4GCZJZ6-5TJ7VCC-PQ62UAL"
    name: "old"
  - id: "FV625Y6-6FYNUO2-YTEI57X-O5M4C3O-4GR3NNY-XQTNHU4-NYO33VW-KCSVPQD"
    name: "old"
  - id: "EE5MZE2-S43AXZE-E4CXK5O-2GVDAFR-7JU6SFP-IN6K3JP-TE3ZRIA-I66JZAP"
    name: "old"
  - id: "6SDZ7WW-TGXASQU-ISK3GIK-X4QK5YJ-3C2ZVYC-YNZRLEQ-XHRP7VE-QFMAOAE"
    name: "old"
  - id: "PQI2PUH-AZUMUC3-Z5XIJVX-IYBKNQ4-YYSDROD-HP2OAOB-OZZ7DEG-BL7WVQZ"
    name: "old"


role_syncthing_user: 'le9i0nx'
role_syncthing_data:
#  devices_add:
#    - "{{ device_moto }}"
  folders:
    - inventory_hosts: '{{ groups.homes }}'
      path: '/home/le9i0nx/crypt'
      id: 'crypt'
      devices_del:
        - '{{ devices_old }}'
    - inventory_hosts: '{{ groups.homes }}'
      path: '/home/le9i0nx/moto_e-photos'
      id: 'moto_e-photos'
      devices_add:
        - "{{ device_moto }}"
      devices_del:
        - '{{ devices_old }}'
    - inventory_hosts: '{{ groups.homes | difference(groups.awz) }}'
      path: '/home/le9i0nx/music'
      id: 'music'
      devices_del:
        - '{{ devices_old }}'
      devices_add:
        - "{{ device_moto }}"
    - inventory_hosts: '{{ groups.homes }}'
      path: '/home/le9i0nx/money'
      id: 'money'
      devices_add:
        - "{{ device_moto }}"
      devices_del:
        - '{{ devices_old }}'
    - inventory_hosts: '{{ groups.homes | difference(groups.awz) }}'
      path: '/home/le9i0nx/rabota'
      id: 'rabota'
      devices_del:
        - '{{ devices_old }}'

## vim: foldmethod=marker:tabstop=2:shiftwidth=2:softtabstop=2
