---

- hosts: all
  become_user: root
  become: False
  gather_facts: no

  tasks:
    - name: install pkg
      raw: apt-get -y install {{item}}
      with_items:
        - python
        - sudo
      changed_when: False

- hosts: all
  become_user: root
  become: True

  roles:

    - role: auth

    - role: users
      tags: [ 'role::users' ]

## vim: foldmethod=marker:tabstop=2:shiftwidth=2:softtabstop=2
