---

- name: Manage OpenSSH Server
  hosts: [ 'debops_all_hosts', 'debops_service_sshd' ]
  become: True

  roles:

    - role: debops.ferm
      tags: [ 'role::ferm' ]
      ferm_dependent_rules:
        - '{{ sshd__ferm__dependent_rules }}'

    - role: debops.sshd
      tags: [ 'role::sshd' ]

## vim: foldmethod=marker:tabstop=2:shiftwidth=2:softtabstop=2
