---

- name: nodm restarted
  service:
    name: 'nodm'
    state: 'restarted'

- name: onboard restarted
  systemd:
    enabled: yes
    name: 'onboard'
    state: 'restarted'
    daemon_reload: yes


## vim: foldmethod=marker:tabstop=2:shiftwidth=2:softtabstop=2
