---

- name: install required packages
  apt:
    name: '{{ item }}'
    state: 'present'
    install_recommends: False
  with_flattened:
    - openresolv
    - wireshark
    - nodm
    - awesome
    - chromium-l10n
    - firefox-esr
    - mplayer
    - rtorrent
    - keepassx
    - shutter
    - xzgv
    - onboard
    - onboard-data
    - xterm
    - xserver-xorg
    - xserver-xorg-core
    - xserver-xorg-input-all
    - xserver-xorg-input-mouse
    - xserver-xorg-input-kbd
    - xserver-xorg-input-multitouch
    - xserver-xorg-input-synaptics
    - x11-xserver-utils
    - x11-utils
    - xserver-xorg-video-all
    - xserver-xorg-video-intel
    - xinput
    - xfonts-base
    - ansible
    - intel-microcode

- name: Create directories
  file:
    path:   '{{ item.path }}'
    state:  '{{ item.state  | default("directory") }}'
    owner:  '{{ item.owner  | default("root") }}'
    group:  '{{ item.group  | default("root") }}'
    mode:   '{{ item.mode   | default("0755") }}'
  with_items:
    - { path: '/home/{{ xorg_user }}/.config/systemd/user/default.target.wants/',owner: '{{ xorg_user }}', group: '{{ xorg_user }}' }
    - { path: '/home/{{ xorg_user }}/.config/awesome' }
    - { path: '/home/{{ xorg_user }}/bin' }

- name: Create symlinks
  file:
    src:    '{{ item.src }}'
    dest:   '{{ item.dest }}'
    state:  '{{ item.state  | default("link") }}'
    owner:  '{{ xorg_user }}'
    group:  '{{ xorg_user }}'
    force:  '{{ item.force  | default("no")}}'
  with_items:
    - { src: '/home/{{ xorg_user }}/config/awesome/lib/debug' , dest: '/home/{{ xorg_user }}/.config/awesome/debug' }
    - { src: '/home/{{ xorg_user }}/config/awesome/lib/lain' , dest: '/home/{{ xorg_user }}/.config/awesome/lain' }
    - { src: '/home/{{ xorg_user }}/config/awesome/lib/tyrannical' , dest: '/home/{{ xorg_user }}/.config/awesome/tyrannical' }
    - { src: '/home/{{ xorg_user }}/config/awesome/lib/zenburn' , dest: '/home/{{ xorg_user }}/.config/awesome/zenburn' }
    - { src: '/home/{{ xorg_user }}/config/awesome/menu/mymenu.lua' , dest: '/home/{{ xorg_user }}/.config/awesome/mymenu.lua' }
    - { src: '/home/{{ xorg_user }}/config/awesome/{{ inventory_hostname }}/rc.lua' , dest: '/home/{{ xorg_user }}/.config/awesome/rc.lua' }
    - { src: '/home/{{ xorg_user }}/config/awesome/{{ inventory_hostname }}/custom.lua' , dest: '/home/{{ xorg_user }}/.config/awesome/custom.lua' }

    - { src: '/home/{{ xorg_user }}/config/bin/vnc_linux.sh' , dest: '/home/{{ xorg_user }}/bin/vnc_linux' }
    - { src: '/home/{{ xorg_user }}/config/bash/bash_aliases' , dest: '/home/{{ xorg_user }}/.bash_aliases' }

- name: add nodm
  template:
    src: etc/default/nodm.j2
    dest: /etc/default/nodm
    owner: root
    group: root
    mode: 0644
  notify:
    - nodm restarted

- name: Copy systemd file
  template:
    src:    'usr/lib/systemd/user/{{ item }}'
    dest:   '/usr/lib/systemd/user/{{ item }}'
    owner:  'root'
    group:  'root'
    mode:   '0644'
  with_items:
    - "onboard.service"
    - "wicd-gtk.service"

- name: Create symlinks systemd
  file:
    src:    '/usr/lib/systemd/user/{{ item }}'
    dest:   '/home/{{ xorg_user }}/.config/systemd/user/default.target.wants/{{ item }}'
    state: link
    owner:  '{{ xorg_user }}'
    group:  '{{ xorg_user }}'
  with_items:
    - "onboard.service"
    - "wicd-gtk.service"

## vim: foldmethod=marker:tabstop=2:shiftwidth=2:softtabstop=2
