---

- name: install required packages
  apt:
    name: '{{ item }}'
    state: 'present'
    install_recommends: False
  with_flattened:
    - 'redshift-gtk'
    - 'geoclue-2.0'

- name: Copy systemd file
  template:
    src:    'usr/lib/systemd/user/{{ item }}'
    dest:   '/usr/lib/systemd/user/{{ item }}'
    owner:  'root'
    group:  'root'
    mode:   '0644'
  with_items:
    - "redshift-gtk.service"

- name: Create symlinks systemd
  file:
    src:    '/usr/lib/systemd/user/{{ item }}'
    dest:   '/home/{{ redshift_user }}/.config/systemd/user/default.target.wants/{{ item }}'
    state: link
    owner:  '{{ redshift_user }}'
    group:  '{{ redshift_user }}'
  with_items:
    - "redshift-gtk.service"

## vim: foldmethod=marker:tabstop=2:shiftwidth=2:softtabstop=2
