---

- name: install required packages
  apt:
    name: '{{ item }}'
    state: 'present'
    install_recommends: False
  with_flattened:
    - unbound

- name: Configure dns
  template:
    src:    'etc/unbound/unbound.conf.d/{{ item }}'
    dest:   '/etc/unbound/unbound.conf.d/{{ item }}'
    owner:  'root'
    group:  'root'
    mode:   '0644'
  with_items:
    - "dns-over-tls.conf"
  notify:
    - 'unbound restarted'


## vim: foldmethod=marker:tabstop=2:shiftwidth=2:softtabstop=2
